### ISSUE TITLE
[Feature Request] Add Chartist plugins support and examples

### ISSUE THREAD

**Issue by pdapnz** [creativetimofficial/ct-vuetify-material-dashboard-pro#29]
### What is your enhancement?
Please provide examples how to use Chartist plugins. 
https://gionkunz.github.io/chartist-js/plugins.html

I tried to use tooltip plugin like this:
https://github.com/tmmdata/chartist-plugin-tooltip/issues/152#issuecomment-395361512

But have not any results, no errors. Nothing. Plugin not work. 

Should plugins work at all?

**Comment by pdapnz** [comment]
The reason of problem was in missing CSS styles. Tooltips was invisible. I added styles and everything became as it should.

Use [fresh fork of original plugin from here](https://github.com/LukBukkit/chartist-plugin-tooltip):
```
yarn add chartist-plugin-tooltips-updated
```
In template section:
```html
  <chartist
    :data="daily"
    :options="options"
    type="Line"
  />
```

Script section:
```javascript
<script>
  import Chartist from 'chartist'
  import * as ChartistTooltips from 'chartist-plugin-tooltips-updated'

  export default {
    props: ['id'],
    data () {
      return {
        daily: [],
        options: {
          plugins: [Chartist.plugins.tooltip()],
          chartPadding: {
            top: 15,
            right: 15,
            bottom: 35,
            left: 30,
          },
        },
```
Styles:

```css
<style>
  .chartist-tooltip {
    position: absolute;
    display: inline-block;
    opacity: 0;
    min-width: 5em;
    padding: .5em;
    background: #E91E63;
    color: white;
    font-family: Oxygen,Helvetica,Arial,sans-serif;
    font-weight: 700;
    text-align: center;
    pointer-events: none;
    z-index: 1;
    -webkit-transition: opacity .2s linear;
    -moz-transition: opacity .2s linear;
    -o-transition: opacity .2s linear;
    transition: opacity .2s linear; }
  .chartist-tooltip:before {
    content: "";
    position: absolute;
    top: 100%;
    left: 50%;
    width: 0;
    height: 0;
    margin-left: -15px;
    border: 15px solid transparent;
    border-top-color: #E91E63; }
  .chartist-tooltip.tooltip-show {
    opacity: 1; }

  .ct-area, .ct-line {
    pointer-events: none; }
</style>
```

Related issues:

https://github.com/tmmdata/chartist-plugin-tooltip/issues/152#issuecomment-395361512

https://github.com/Yopadd/vue-chartist/issues/32#issuecomment-424499804
